apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc
spec:
  selector:
    matchLabels:
      app: kc
  replicas: 1
  template:
    metadata:
      labels:
        app: kc
    spec:
      containers:
        - name: kc
          image: mykc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "750m"
              memory: "1024Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"